# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/coordinate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/coordinate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16proto/coordinate.proto\"\x1b\n\x0b\x43oorRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\"=\n\x0c\x43oorResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01(\t2=\n\nCubeFinder\x12/\n\x0egetCoordinates\x12\x0c.CoorRequest\x1a\r.CoorResponse\"\x00\x62\x06proto3')
)




_COORREQUEST = _descriptor.Descriptor(
  name='CoorRequest',
  full_name='CoorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='CoorRequest.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=53,
)


_COORRESPONSE = _descriptor.Descriptor(
  name='CoorResponse',
  full_name='CoorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='CoorResponse.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='CoorResponse.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='CoorResponse.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='CoorResponse.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['CoorRequest'] = _COORREQUEST
DESCRIPTOR.message_types_by_name['CoorResponse'] = _COORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoorRequest = _reflection.GeneratedProtocolMessageType('CoorRequest', (_message.Message,), dict(
  DESCRIPTOR = _COORREQUEST,
  __module__ = 'proto.coordinate_pb2'
  # @@protoc_insertion_point(class_scope:CoorRequest)
  ))
_sym_db.RegisterMessage(CoorRequest)

CoorResponse = _reflection.GeneratedProtocolMessageType('CoorResponse', (_message.Message,), dict(
  DESCRIPTOR = _COORRESPONSE,
  __module__ = 'proto.coordinate_pb2'
  # @@protoc_insertion_point(class_scope:CoorResponse)
  ))
_sym_db.RegisterMessage(CoorResponse)



_CUBEFINDER = _descriptor.ServiceDescriptor(
  name='CubeFinder',
  full_name='CubeFinder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=118,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCoordinates',
    full_name='CubeFinder.getCoordinates',
    index=0,
    containing_service=None,
    input_type=_COORREQUEST,
    output_type=_COORRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUBEFINDER)

DESCRIPTOR.services_by_name['CubeFinder'] = _CUBEFINDER

# @@protoc_insertion_point(module_scope)
