# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import coordinate_pb2 as proto_dot_coordinate__pb2


class CubeFinderStub(object):
  """import "google/protobuf/empty.proto";

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCoordinates = channel.unary_unary(
        '/CubeFinder/getCoordinates',
        request_serializer=proto_dot_coordinate__pb2.CoorRequest.SerializeToString,
        response_deserializer=proto_dot_coordinate__pb2.CoorResponse.FromString,
        )


class CubeFinderServicer(object):
  """import "google/protobuf/empty.proto";

  """

  def getCoordinates(self, request, context):
    """rpc getCoordinates (google.protobuf.Empty) returns (Coordinates) {}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CubeFinderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCoordinates': grpc.unary_unary_rpc_method_handler(
          servicer.getCoordinates,
          request_deserializer=proto_dot_coordinate__pb2.CoorRequest.FromString,
          response_serializer=proto_dot_coordinate__pb2.CoorResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CubeFinder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
