global:
  scrape_interval: 2s

  external_labels:
    monitor: 'grpc-helloworld'

scrape_configs:
  - job_name: 'grpc-helloworld'

    scrape_interval: 2s

    static_configs:
      - targets: ['localhost:8888']
